version: '3'

services:
  dev-db:
    image: postgres:14.2
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  test-db:
    image: postgres:14.2
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  redis:
    image: redis:7
    restart: always
    ports:
      - ${REDIS_PORT}:6379
